<?php

declare(strict_types=1);

namespace Doxestic\DeathAnimation;

use Doxestic\DeathAnimation\Events\PlayerDeath;
use Doxestic\DeathAnimation\HeadEntity\Head;
use pocketmine\entity\Entity;
use pocketmine\plugin\PluginBase;
use pocketmine\utils\Config;

class Main extends PluginBase{

	public const PREFIX = "§a[ §bPlayer Death Animation §a] §d";

	public $config;

	public function onEnable()
	{
		Entity::registerEntity(Head::class, true);
		$this->saveResource("config.yml");
		$this->config = new Config($this->getDataFolder()."config.yml", Config::YAML);
		$this->getServer()->getPluginManager()->registerEvents(new PlayerDeath($this), $this);
		$this->getServer()->getLogger()->info(self::PREFIX."Plugin Enabled");
		parent::onEnable(); // TODO: Change the autogenerated stub
	}
}
